name: FanFox.net
author: Zyrouge
repo:
    username: yukino-org
    repo: tenka-modules
    ref: 5217dd3ff6146bb267a320235f8bf78de7d6cf4c
source:
    root: modules/manga/fanfox_net/src
    file: main.fbs
thumbnail: modules/manga/fanfox_net/logo.png
nsfw: false
