name: FanFox.net
author: Zyrouge
repo:
    username: yukino-org
    repo: official-tenka-modules
    ref: e7649808be866341a1918c0d1e2d58a0e28b9b50
source:
    root: modules/manga/fanfox_net/src
    file: main.ht
thumbnail: modules/manga/fanfox_net/logo.png
nsfw: false
