name: GogoAnime.pe
author: Zyrouge
repo:
    username: yukino-org
    repo: official-tenka-modules
    ref: 18a69e963fc4d5e788f96902a25bacbe72a23885
source:
    root: modules/anime/gogoanime_pe/src
    file: main.ht
thumbnail: modules/anime/gogoanime_pe/logo.png
nsfw: false
