name: GogoAnime.pe
author: Zyrouge
repo:
    username: yukino-org
    repo: official-tenka-modules
    ref: 246c5d035005cd1f70ffe88e4f14f20b69925a59
source:
    root: modules/anime/gogoanime_pe/src
    file: main.ht
thumbnail: modules/anime/gogoanime_pe/logo.png
nsfw: false
