name: GogoAnime.pe
author: Zyrouge
repo:
    username: yukino-org
    repo: tenka-modules
    ref: 3b174edfe4574cd72f3fcd6150e61df0c48e6852
source:
    root: modules/anime/gogoanime_pe/src
    file: main.ht
thumbnail: modules/anime/gogoanime_pe/logo.png
nsfw: false
