name: GogoAnime.pe
author: Zyrouge
repo:
    username: yukino-org
    repo: tenka-modules
    ref: b3ddddd3e195857c607d1b5e9d6747f0e47c2784
source:
    root: modules/anime/gogoanime_pe/src
    file: main.ht
thumbnail: modules/anime/gogoanime_pe/logo.png
nsfw: false
