name: GogoAnime.pe
author: Zyrouge
repo:
    username: yukino-org
    repo: official-tenka-modules
    ref: d19ef50236cb83b65cc109ec6e28fcaba0ffe00a
source:
    root: modules/anime/gogoanime_pe/src
    file: main.ht
thumbnail: modules/anime/gogoanime_pe/logo.png
nsfw: false
