name: AnimePahe.com
author: Zyrouge
repo:
    username: yukino-org
    repo: official-tenka-modules
    ref: 71a31c9589965de66e7b6c52afb6a696775af4ab
source:
    root: modules/anime/animepahe_com/src
    file: main.ht
thumbnail: modules/anime/animepahe_com/logo.png
nsfw: false
