name: AnimePahe.com
author: Zyrouge
repo:
    username: yukino-org
    repo: official-tenka-modules
    ref: e7649808be866341a1918c0d1e2d58a0e28b9b50
source:
    root: modules/anime/animepahe_com/src
    file: main.ht
thumbnail: modules/anime/animepahe_com/logo.png
nsfw: false
disabled: true
