name: AnimePahe.com
author: Zyrouge
repo:
    username: yukino-org
    repo: official-tenka-modules
    ref: 18a69e963fc4d5e788f96902a25bacbe72a23885
source:
    root: modules/anime/animepahe_com/src
    file: main.ht
thumbnail: modules/anime/animepahe_com/logo.png
nsfw: false
disabled: true
