name: AnimePahe.com
author: Zyrouge
repo:
    username: yukino-org
    repo: tenka-modules
    ref: 37100c0809f707bbfc42755d70225f328ca2c0dd
source:
    root: modules/anime/animepahe_com/src
    file: main.ht
thumbnail: modules/anime/animepahe_com/logo.png
nsfw: false
disabled: true
