name: HAnime.tv
author: Zyrouge
repo:
    username: yukino-org
    repo: official-tenka-modules
    ref: d19ef50236cb83b65cc109ec6e28fcaba0ffe00a
source:
    root: modules/anime/hanime_tv/src
    file: main.ht
thumbnail: modules/anime/hanime_tv/logo.png
nsfw: true
