name: HAnime.tv
author: Zyrouge
repo:
    username: yukino-org
    repo: official-tenka-modules
    ref: 6685fab2dffacd874d83d25c3aea2dadeac2a172
source:
    root: modules/anime/hanime_tv/src
    file: main.ht
thumbnail: modules/anime/hanime_tv/logo.png
nsfw: true
