name: HAnime.tv
author: Zyrouge
repo:
    username: yukino-org
    repo: official-tenka-modules
    ref: 2a0868816400841ccd21e629e9d74dd4723481c1
source:
    root: modules/anime/hanime_tv/src
    file: main.ht
thumbnail: modules/anime/hanime_tv/logo.png
nsfw: true
