name: HAnime.tv
author: Zyrouge
repo:
    username: yukino-org
    repo: tenka-modules
    ref: 3b174edfe4574cd72f3fcd6150e61df0c48e6852
source:
    root: modules/anime/hanime_tv/src
    file: main.ht
thumbnail: modules/anime/hanime_tv/logo.png
nsfw: true
