name: HAnime.tv
author: Zyrouge
repo:
    username: yukino-org
    repo: official-tenka-modules
    ref: 9daac58284075e9d92cfe50864ed9cbb4b2b2a55
source:
    root: modules/anime/hanime_tv/src
    file: main.ht
thumbnail:
    root: modules/anime/hanime_tv
    file: logo.png
nsfw: true
