name: HAnime.tv
author: Zyrouge
repo:
    username: yukino-org
    repo: official-tenka-modules
    ref: e9574fc26f9ac71ddd7dfb4902acbc9427ac2462
source:
    root: modules/anime/hanime_tv/src
    file: main.ht
thumbnail: modules/anime/hanime_tv/logo.png
nsfw: true
