name: Tenshi.moe
author: Zyrouge
repo:
    username: yukino-org
    repo: official-tenka-modules
    ref: 9daac58284075e9d92cfe50864ed9cbb4b2b2a55
source:
    root: modules/anime/tenshi_moe/src
    file: main.ht
thumbnail: modules/anime/tenshi_moe/logo.png
nsfw: false
