name: Twist.moe
author: Zyrouge
repo:
    username: yukino-org
    repo: official-tenka-modules
    ref: 6685fab2dffacd874d83d25c3aea2dadeac2a172
source:
    root: modules/anime/twist_moe/src
    file: main.ht
thumbnail: modules/anime/twist_moe/logo.png
nsfw: false
