name: Twist.moe
author: Zyrouge
repo:
    username: yukino-org
    repo: tenka-modules
    ref: b3ddddd3e195857c607d1b5e9d6747f0e47c2784
source:
    root: modules/anime/twist_moe/src
    file: main.ht
thumbnail: modules/anime/twist_moe/logo.png
nsfw: false
disabled: true
