name: Twist.moe
author: Zyrouge
repo:
    username: yukino-org
    repo: official-tenka-modules
    ref: 9daac58284075e9d92cfe50864ed9cbb4b2b2a55
source:
    root: modules/anime/twist_moe/src
    file: main.ht
thumbnail:
    root: modules/anime/twist_moe
    file: logo.png
nsfw: false
