name: Twist.moe
author: Zyrouge
repo:
    username: yukino-org
    repo: official-tenka-modules
    ref: 71a31c9589965de66e7b6c52afb6a696775af4ab
source:
    root: modules/anime/twist_moe/src
    file: main.ht
thumbnail: modules/anime/twist_moe/logo.png
nsfw: false
