name: Twist.moe
author: Zyrouge
repo:
    username: yukino-org
    repo: official-tenka-modules
    ref: 6604becc94f3ee3d842da46e5a16250197f3c8cd
source:
    root: modules/anime/twist_moe/src
    file: main.ht
thumbnail: modules/anime/twist_moe/logo.png
nsfw: false
