name: GogoAnime.pe
author: Zyrouge
repo:
    username: yukino-app
    repo: official-extensions
    ref: 724fc16638726580ff2b82886b26c3816895fa87
source:
    root: extensions/anime/gogoanime_pe/src
    file: main.ht
thumbnail:
    root: extensions/anime/gogoanime_pe
    file: logo.png
nsfw: false
