name: MangaSee123.com
author: Zyrouge
repo:
    username: yukino-org
    repo: tenka-modules
    ref: b3ddddd3e195857c607d1b5e9d6747f0e47c2784
source:
    root: modules/manga/mangasee123_com/src
    file: main.ht
thumbnail: modules/manga/mangasee123_com/logo.png
nsfw: false
