name: ReadM.org
author: Zyrouge
repo:
    username: yukino-org
    repo: tenka-modules
    ref: 5217dd3ff6146bb267a320235f8bf78de7d6cf4c
source:
    root: modules/manga/readm_org/src
    file: main.fbs
thumbnail: modules/manga/readm_org/logo.png
nsfw: false
