name: ReadM.org
author: Zyrouge
repo:
    username: yukino-org
    repo: official-tenka-modules
    ref: 6685fab2dffacd874d83d25c3aea2dadeac2a172
source:
    root: modules/manga/readm_org/src
    file: main.ht
thumbnail: modules/manga/readm_org/logo.png
nsfw: false
