name: ReadM.org
author: Zyrouge
repo:
    username: yukino-org
    repo: official-tenka-modules
    ref: e9574fc26f9ac71ddd7dfb4902acbc9427ac2462
source:
    root: modules/manga/readm_org/src
    file: main.ht
thumbnail: modules/manga/readm_org/logo.png
nsfw: false
