name: ReadM.org
author: Zyrouge
repo:
    username: yukino-org
    repo: tenka-modules
    ref: 37100c0809f707bbfc42755d70225f328ca2c0dd
source:
    root: modules/manga/readm_org/src
    file: main.ht
thumbnail: modules/manga/readm_org/logo.png
nsfw: false
