name: ReadM.org
author: Zyrouge
repo:
    username: yukino-org
    repo: official-tenka-modules
    ref: 6604becc94f3ee3d842da46e5a16250197f3c8cd
source:
    root: modules/manga/readm_org/src
    file: main.ht
thumbnail: modules/manga/readm_org/logo.png
nsfw: false
