name: ReadM.org
author: Zyrouge
repo:
    username: yukino-org
    repo: official-tenka-modules
    ref: 246c5d035005cd1f70ffe88e4f14f20b69925a59
source:
    root: modules/manga/readm_org/src
    file: main.ht
thumbnail: modules/manga/readm_org/logo.png
nsfw: false
