name: GogoAnime.bid
author: Zyrouge
repo:
    username: yukino-org
    repo: tenka-modules
    ref: 804d6353a865701c45272da33d535ffc5d7ca2a2
source:
    root: modules/anime/gogoanime_bid/src
    file: main.fbs
thumbnail: modules/anime/gogoanime_bid/logo.png
nsfw: false
