name: ReadM.org
author: Zyrouge
repo:
    username: yukino-app
    repo: official-extensions
    ref: 724fc16638726580ff2b82886b26c3816895fa87
source:
    root: extensions/manga/readm_org/src
    file: main.ht
thumbnail:
    root: extensions/manga/readm_org
    file: logo.png
nsfw: false
