name: MangaDex.org
author: Zyrouge
repo:
    username: yukino-org
    repo: tenka-modules
    ref: b3ddddd3e195857c607d1b5e9d6747f0e47c2784
source:
    root: modules/manga/mangadex_org/src
    file: main.ht
thumbnail: modules/manga/mangadex_org/logo.png
nsfw: false
