name: MangaDex.org
author: Zyrouge
repo:
    username: yukino-org
    repo: tenka-modules
    ref: e7649808be866341a1918c0d1e2d58a0e28b9b50
source:
    root: modules/manga/mangadex_org/src
    file: main.ht
thumbnail: modules/manga/mangadex_org/logo.png
nsfw: false
