name: MangaDex.org
author: Zyrouge
repo:
    username: yukino-org
    repo: official-tenka-modules
    ref: 9daac58284075e9d92cfe50864ed9cbb4b2b2a55
source:
    root: modules/manga/mangadex_org/src
    file: main.ht
thumbnail: modules/manga/mangadex_org/logo.png
nsfw: false
