name: MangaDex.org
author: Zyrouge
repo:
    username: yukino-org
    repo: official-tenka-modules
    ref: d19ef50236cb83b65cc109ec6e28fcaba0ffe00a
source:
    root: modules/manga/mangadex_org/src
    file: main.ht
thumbnail: modules/manga/mangadex_org/logo.png
nsfw: false
