name: MangaDex.org
author: Zyrouge
repo:
    username: yukino-org
    repo: official-tenka-modules
    ref: 18a69e963fc4d5e788f96902a25bacbe72a23885
source:
    root: modules/manga/mangadex_org/src
    file: main.ht
thumbnail: modules/manga/mangadex_org/logo.png
nsfw: false
