name: MangaDex.org
author: Zyrouge
repo:
    username: yukino-org
    repo: tenka-modules
    ref: 3b174edfe4574cd72f3fcd6150e61df0c48e6852
source:
    root: modules/manga/mangadex_org/src
    file: main.ht
thumbnail: modules/manga/mangadex_org/logo.png
nsfw: false
