name: MangaDex.org
author: Zyrouge
repo:
    username: yukino-org
    repo: official-tenka-modules
    ref: 71a31c9589965de66e7b6c52afb6a696775af4ab
source:
    root: modules/manga/mangadex_org/src
    file: main.ht
thumbnail: modules/manga/mangadex_org/logo.png
nsfw: false
