name: Tenshi.moe
author: Zyrouge
repo:
    username: yukino-org
    repo: official-extensions
    ref: 724fc16638726580ff2b82886b26c3816895fa87
source:
    root: extensions/anime/tenshi_moe/src
    file: main.ht
thumbnail:
    root: extensions/anime/tenshi_moe
    file: logo.png
nsfw: false
