name: Zoro.to
author: Zyrouge
repo:
    username: yukino-org
    repo: official-tenka-modules
    ref: e7649808be866341a1918c0d1e2d58a0e28b9b50
source:
    root: modules/anime/zoro_to/src
    file: main.ht
thumbnail: modules/anime/zoro_to/logo.png
nsfw: false
