name: Zoro.to
author: Zyrouge
repo:
    username: yukino-org
    repo: official-tenka-modules
    ref: eb13d9e3ec63c070f98eb12a858bbec9d83e3d2d
source:
    root: modules/anime/zoro_to/src
    file: main.ht
thumbnail:
    root: modules/anime/zoro_to
    file: logo.png
nsfw: false
