name: Zoro.to
author: Zyrouge
repo:
    username: yukino-org
    repo: official-tenka-modules
    ref: 38f3fc3a889a98e299b1cefcf43426bd1de4aa4c
source:
    root: modules/anime/zoro_to/src
    file: main.ht
thumbnail:
    root: modules/anime/zoro_to
    file: logo.png
nsfw: false
