name: Zoro.to
author: Zyrouge
repo:
    username: yukino-org
    repo: tenka-modules
    ref: 3b174edfe4574cd72f3fcd6150e61df0c48e6852
source:
    root: modules/anime/zoro_to/src
    file: main.ht
thumbnail: modules/anime/zoro_to/logo.png
nsfw: false
