name: Deploy

on:
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - uses: dart-lang/setup-dart@v1

            - run: dart pub get
              working-directory: ./lib

            - run: dart run ./src/commands/build.dart
              working-directory: ./lib

            - uses: JamesIves/github-pages-deploy-action@4.1.4
              with:
                  branch: dist
                  folder: dist
