name: Deploy

on:
    workflow_dispatch:

env:
    STORE_WORKING_DIR: ./lib
    GENERATED_GLOB: modules/**/_data.json
    DEPLOY_BRANCH: dist
    DEPLOY_DIR: dist
    DEPLOY_MODE: next
    GIT_CONFIG_NAME: "[Automated] Yui"
    GIT_CONFIG_EMAIL: yukino-org@users.noreply.github.com
    GIT_COMMIT_MSG: "[automated] update data files (${{ github.sha }})"

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - uses: dart-lang/setup-dart@v1

            - name: 🚧 Do prerequisites
              run: dart pub get
              working-directory: ${{ env.STORE_WORKING_DIR }}

            - name: 🔨 Build store
              run: dart run ./src/commands/build/run.dart
              working-directory: ${{ env.STORE_WORKING_DIR }}

            - name: 🚀 Update store
              uses: JamesIves/github-pages-deploy-action@4.1.4
              with:
                  branch: ${{ env.DEPLOY_BRANCH }}
                  folder: ${{ env.DEPLOY_DIR }}
                  commit-message: ${{ env.GIT_COMMIT_MSG }}
                  git-config-name: ${{ env.GIT_CONFIG_NAME }}
                  git-config-email: ${{ env.GIT_CONFIG_EMAIL }}

            - name: 🚀 Update data files
              run: |
                  git config --local user.name "${{ env.GIT_CONFIG_NAME }}"
                  git config --local user.email "${{ env.GIT_CONFIG_EMAIL }}"
                  git add ${{ env.GENERATED_GLOB }}
                  git commit --allow-empty -m "${{ env.GIT_COMMIT_MSG }}"
                  git push
