name: Deploy (Next)

on:
    workflow_dispatch:

env:
    DEPLOY_MODE: next

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-dart@v1

            - run: dart pub get

            - run: dart run ./src/commands/build.dart
              working-directory: ./lib

            # - uses: JamesIves/github-pages-deploy-action@4.1.4
            #   with:
            #       branch: dist-${{ env.DEPLOY_MODE }}
            #       folder: dist
