name: Test (Pull request)

on:
    pull_request:
        - ready_for_review
        - review_requested

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: 16.x
                  cache: npm
                  cache-dependency-path: lib/package-lock.json

            - run: npm ci && npm run scenario:pr -- ${{ github.event.number }}
              working-directory: ./lib
